SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E JOIN HR_GRADE G ON D.DEPT_ID = E.DEPT_ID AND E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
